config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'

  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/welcome/:first_name', to: 'landing_pages#welcome'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:create, :edit, :update, :destroy]
  before_action :is_my_comment, only: [:edit, :update, :destroy]


  def create
    @comment = Comment.new('content' => params[:content], 'gossip_id' => params[:gossip_id],'user_id' => current_user.id)
    if @comment.save
      redirect_to gossip_path(@comment.gossip.id), notice: "Commentaire créé avec succès"
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    comment_params = params.require(:comment).permit(:content, :gossip_id)
    if @comment.update(content: params[:content], gossip_id: params[:gossip_id])
      redirect_to gossip_path(@comment.gossip.id), notice:"Ton commentaire a été mis à jour !"
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to gossip_path(@comment.gossip.id)
  end


  private

  def is_my_comment
    @comment = Comment.find(params[:id])
    unless current_user == @comment.user
      flash[:danger] = "Ce n'est pas votre commentaire"
      redirect_to gossip_path(@comment.gossip.id)
    end
  end
  # GET /comments/1/edit
  # def edit
  #   params.require(:comment).permit(:title, :content)
  # end

  # POST /comments
  # POST /comments.json


  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json

#
#   # DELETE /comments/1
#   # DELETE /comments/1.json
#   def destroy
#     @comment.destroy
#     respond_to do |format|
#       format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end
#
#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_comment
#       @comment = Comment.find(params[:id])
#     end
#
#     # Only allow a list of trusted parameters through.
#     def comment_params
#       params.require(:comment).permit(:title, :content)
#     end
end

app/helpers/comments_helper.rb
module CommentsHelper


end

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
<div class="alert alert-danger text-center" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="container">
  <h1 class="text-center my-5"> Modifier le commentaire</h1>
  <div class="col-12">
    <div class="shadow-none bg-light rounded p-4">
      <%= form_tag gossip_comment_path(@comment.gossip.id, @comment.id), method: "put" do %>
        <%= label_tag 'Contenu du commentaire' %>
        <%= text_area_tag 'content', "#{@comment.content}", class: "form-control" %><br>
        <%= submit_tag "Sauvegarder",  class: "btn btn-primary" %>
        <%= link_to  "Supprimer", gossip_comment_path(@comment.gossip.id), method: :delete, data:{confirm: "Tu veux vraiment supprimer ton commentaire ?"}, class:"btn btn-danger" %><br>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<% if @comment.errors.any? %>
<div class="alert alert-danger text-center" role="alert">
  <p>Nous n'avons pas réussi à créer le commentaire pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @comment.errors.full_messages.each do |comment| %>
    <li><%= comment %></li>
    <% end %>
  </ul>
</div>
<% end %>

<h1 class="m-4 text-center"> Nouveau commentaire </h1>
<div class= "container d-flex justify-content-center">
  <div class="form-group col-8">
    <%= form_tag url_for(action: 'create'), method: "post" do %>

    <%= label_tag 'Content' %>
    <%= text_area_tag 'content', @comment.content, class: "form-control"%>
    <br /> <br />

    <%= submit_tag "Créer commentaire",  class: "btn btn-primary" %>

    <% end %>
  </div>
</div>