config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'

  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/welcome/:first_name', to: 'landing_pages#welcome'
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :likes


  def remember(remember_token)
   remember_digest = BCrypt::Password.create(remember_token)
   self.update(remember_digest: remember_digest)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new('first_name' => params[:first_name], email: params[:email], password: params[:password], city_id: params[:city_id])
    if @user.save
      session[:user_id] = @user.id
      # log_in(@user)
      if params[:remember_token]
        remember(@user)
      end
      redirect_to root_path, notice: "Bienvenu "
    else
      render :new
    end
  end

  # def edit
  #   @user = Gossip.find(params[:id])
  # end
  #
  # def update
  #   @user = Gossip.find(params[:id])
  #   user_params = params.require(:user).permit(:title, :content)
  #   if @user.update(user_params)
  #     redirect_to @user, notice:"Ton potin a été mis à jour !"
  #   else
  #     render :edit
  #   end
  # end
  #
  # def destroy
  #   @user = Gossip.find(params[:id])
  #   @user.destroy
  #   redirect_to root_path
  # end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="text-center mt-5">
  <div class="m-auto" style="width: 300px">
    <%= form_tag url_for(action: 'create'), method: "post", class: "form-signin" do %>
    <h1 class="h3 mb-3 font-weight-normal">Inscription</h1>
    <%= text_field_tag 'first_name', "", class: "form-control", placeholder: 'Prénom'  %>
    <%= select_tag "city_id", options_from_collection_for_select(City.all, "id", "name"), class:"form-control", required:"required"%>
    <%= text_field_tag 'email', "", class: "form-control", placeholder: 'Email' %>
    <%= password_field_tag 'password',"", class: "form-control", placeholder: 'Mot de passe' %>
    <div class="custom-control custom-checkbox mb-3">
      <input type="checkbox" name='remember_token'class="custom-control-input" id="customCheck1">
      <label class="custom-control-label" for="customCheck1">Se souvenir de moi ?</label>
    </div>
    <%= submit_tag "S'inscrire",  class: "btn btn-lg btn-primary btn-block" %>
    <% end %>
    <p class="mt-5 mb-3 text-muted">&copy; 2020-2021</p>
  </div>
</div>

app/views/users/show.html.erb
<div class="container text-center">

  <h1 class="text-center m-5">
    Utilisateur
  </h1>
  <div class="row">
    <div class="col-md-12 col-lg-4 px-3">
      <div class="bg-light rounded border text-left px-4">
        <h2 class="my-4 text-center">Profil</h2>
        <p> Nom : <%= @user.last_name %></p>
        <p> Prénom : <%= @user.first_name %></p>
        <p> Age : <%= @user.age %> </p>
        <p> Description : <%= @user.description %></p>
        <p> Ville : <%= link_to "#{@user.city.name}", city_path(@user.city) %>
      </div>
    </div>
    <div class="col-md-12 col-lg-8 px-3">
      <div class="px-3">


      <h2 class="my-4">Les Potins de <%= @user.first_name %></h2>
      <div class="row justify-content-center text-left">
        <% @user.gossips.each do |gossip| %>


        <div class="card mx-3 mb-4 shadow-sm col-12">
          <div class="card-body">
            <div class="text-right">
              <small class="text-muted"><%= gossip.updated_at.strftime("%d/%m/%Y")%></small>
            </div>
            <h5 class="card-title"><%=gossip.title%></h5>
            <p class="card-text"><%= truncate(gossip.content, length: 50) %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="">
                <%= link_to "Voir", gossip_path(gossip.id), class: "btn btn-outline-secondary btn-sm" %>
                <small class="text-muted">
                  <%if gossip.comments.count > 1%>
                  <%=gossip.comments.count%> commentaires
                  <%elsif gossip.comments.count == 0%>
                  Pas de commentaire
                  <%else%>
                  <%=gossip.comments.count%> commentaire
                  <%end %>
                </small>
              </div>
              <small class="text-muted">Ecrit par <%= link_to gossip.user.first_name, user_path(gossip.user.id) %></small>
            </div>
          </div>
        </div>
        <% end %>
      </div>
</div>
    </div>

    </div>
  </div>