config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'

  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/welcome/:first_name', to: 'landing_pages#welcome'
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :gossip_tags, dependent: :destroy
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy


  def comment_count
    comments.count
  end

  def like_count
    likes.count
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :show, :create, :edit, :update, :destroy]
  before_action :is_my_gossip, only: [:edit, :update, :destroy]


  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new('title' => params[:title], 'content' => params[:content], 'user_id' =>  current_user.id)
    if @gossip.save
      redirect_to gossip_path(@gossip.id), notice: "Gossip créé avec succès"
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(gossip_params)
      redirect_to gossip_path(@gossip.id), notice:"Ton potin a été mis à jour !"
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

  private

  def is_my_gossip
    @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user
      flash[:danger] = "Ce n'est pas votre potin"
      redirect_to gossip_path(@gossip.id)
    end
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper



end

app/views/gossips/edit.html.erb
<% if @gossip.errors.any? %>
<div class="alert alert-danger text-center" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="container">
  <h1 class="text-center my-5"> Modifier le potin</h1>
  <div class="col-12">
    <div class="shadow-none bg-light rounded p-4">
      <%= form_for @gossip, url: {action: "update"} do |f| %>
        <%= label_tag 'Title' %>
        <%= f.text_field :title, class: "form-control mb-4" %>
        <%= label_tag 'Content' %>
        <%= f.text_area :content, class: "form-control mb-4" %>
        <%= f.submit "Sauvegarder", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/gossips/index.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="display-3">The Gossip Project</h1>
    <p>Amour, Sexe, Drogue, découvrez tous les derniers Gossips</p>
    <%= link_to "Créer un gossip", new_gossip_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <% @gossips.each do |gossip| %>

    <div class="col-sm-6 col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <div class="text-right">
              <small class="text-muted"><%= gossip.updated_at.strftime("%d/%m/%Y")%></small>
            </div>
            <h5 class="card-title"><%=gossip.title%></h5>
            <p class="card-text"><%= truncate(gossip.content, length: 50) %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="text-left">
                <% if current_user %>
                  <% if already_liked?(current_user, gossip)%>
                    <small class="text-muted"><%= link_to "J'aime pas", gossip_like_path(gossip.id, get_like(current_user, gossip).id), method: :delete %></small>
                  <%else %>
                    <small class="text-muted"><%= link_to "J'aime", gossip_likes_path(gossip.id), method: :post %></small>
                  <% end %>
                    <small class="text-muted"> <%= gossip.like_count %></small>
                <% else %>
                  <small class="text-muted"><%= gossip.like_count %>Like</small>
                <% end %>
              </div>
              <div class="text-right">
                <small class="text-muted">
                  <%if gossip.comment_count > 1%>
                    <%=gossip.comment_count%> commentaires
                  <%elsif gossip.comment_count == 0%>
                    Aucun commentaire
                  <%else%>
                    <%=gossip.comment_count%> commentaire
                  <%end %>
                </small>
              </div>
            </div>
            <div class="d-flex justify-content-between align-items-center">
              <div class="">
                <%= link_to "Voir", gossip_path(gossip.id), class: "btn btn-outline-secondary btn-sm" %>
              </div>
              <small class="text-muted">Ecrit par <%= link_to gossip.user.first_name, user_path(gossip.user.id) %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>


</div>

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
<div class="alert alert-danger text-center" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="container">
  <h1 class="text-center my-5"> Nouveau potin</h1>
  <div class="col-12">
    <div class="shadow-none bg-light rounded p-4">
      <%= form_tag url_for(action: 'create'), method: "post" do %>
      <%= label_tag 'Titre du Gossip' %>
      <%= text_field_tag 'title', @gossip.title, class: "form-control" %><br>
      <%= label_tag 'Contennu de mon Gossip' %>
      <%= text_area_tag 'content', @gossip.content, class: "form-control"%><br>
      <%= submit_tag "Créer le Gossip",  class: "btn btn-primary" %>

      <% end %>
    </div>
  </div>
</div>

app/views/gossips/show.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-success text-center" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>


<div class="container py-5">
  <div class="row">
    <div class="col-12 px-3">
      <div class="bg-light rounded border text-left p-4">
        <div class="text-right">
          Créé le <%= @gossip.created_at.strftime("%d/%m/%Y") %>
        </div>
        <h1> <%= @gossip.title %> </h1>
        <p> <%= @gossip.content %> </p>
        <p>
          Par <%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %>
          à <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city) %>
        </p>

        <div class="text-left">
          <% if current_user %>
            <% if already_liked?(current_user, @gossip)%>
              <small class="text-muted"><%= link_to "J'aime pas", gossip_like_path(@gossip.id, get_like(current_user, @gossip).id), method: :delete %></small>
            <%else %>
              <small class="text-muted"><%= link_to "J'aime", gossip_likes_path(@gossip.id), method: :post %></small>
            <% end %>
            <small class="text-muted"> <%= @gossip.like_count %></small>
          <% else %>
            <small class="text-muted"><%= @gossip.like_count %> Like</small>
          <% end %>
        </div>
        <div class="text-right">
          <% if is_mine(@gossip, current_user) %>
            <%= link_to "Retourner aux Gossips", root_path, :class => "btn btn-link" %>
            <%= link_to "Modifier", edit_gossip_path, :class => "btn btn-outline-primary" %>
            <%= link_to  "Supprimer", gossip_path(@gossip.id), method: :delete, data:{confirm: "Tu veux vraiment supprimer ce potin ?"}, class:"btn btn-outline-danger" %>
          <%else%>
            <%= link_to "Retourner aux Gossips", root_path, :class => "btn btn-link" %>
          <%end%>
        </div>
      </div>
    </div>

    <div class="col-12 px-3 mt-4">
      <div class="bg-light rounded border text-left p-3">
        <h2 class="m-4">Commentaires </h2>

          <div class="form-group m-3">
            <%= form_tag gossip_comments_path(@gossip.id), method: "post" do %>
              <%= label_tag 'Écrire un commentaire' %>
              <%= text_area_tag 'content', "", class: "form-control" %>
              <%= submit_tag "Créer commentaire",  class: "btn btn-primary my-4" %>
            <% end %>
          </div>

        <% @gossip.comments.each do |comment| %>
          <div class="list-group m-3">
            <div class="list-group-item list-group-item-action">
              <div class="text-right">
                <small><%= comment.created_at.strftime("%d/%m/%Y")%></small>
              </div>
              <p class="mb-1"><%= comment.content %></p>
              <small>
                Par <%= link_to "#{comment.user.first_name}", user_path(comment.user.id) %>
              </small><br>
              <% if is_mine(comment, current_user) %>
                <div class="text-right">
                  <%= link_to "Modifier", edit_gossip_comment_path(@gossip.id, comment.id), class:"btn btn-outline-primary btn-sm" %>
                  <%= link_to  "Supprimer", gossip_comment_path(@gossip.id, comment.id), method: :delete, data:{confirm: "Tu veux vraiment supprimer ton commentaire ?"}, class:"btn btn-outline-danger btn-sm" %><br>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    </div>
  </div>