config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'

  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  get '/welcome/:first_name', to: 'landing_pages#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :gossip_tags, dependent: :destroy
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy


  def comment_count
    comments.count
  end

  def like_count
    likes.count
  end

end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags, dependent: :destroy
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :likes


  def remember(remember_token)
   remember_digest = BCrypt::Password.create(remember_token)
   self.update(remember_digest: remember_digest)
 end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user

  def create
    if already_liked?
      flash[:notice] = "Déjà liké"
    else
      @like = Like.create(user_id: current_user.id, gossip_id: params[:gossip_id])
    end
    redirect_to root_path
  end

  def find_like
   @like = @gossip.likes.find(params[:id])
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, gossip_id: params[:gossip_id])
    @like.destroy
    redirect_to root_path
  end


  private

  def already_liked?
    Like.where(user_id: current_user.id, gossip_id: params[:gossip_id]).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new('first_name' => params[:first_name], email: params[:email], password: params[:password], city_id: params[:city_id])
    if @user.save
      session[:user_id] = @user.id
      # log_in(@user)
      if params[:remember_token]
        remember(@user)
      end
      redirect_to root_path, notice: "Bienvenu "
    else
      render :new
    end
  end

  # def edit
  #   @user = Gossip.find(params[:id])
  # end
  #
  # def update
  #   @user = Gossip.find(params[:id])
  #   user_params = params.require(:user).permit(:title, :content)
  #   if @user.update(user_params)
  #     redirect_to @user, notice:"Ton potin a été mis à jour !"
  #   else
  #     render :edit
  #   end
  # end
  #
  # def destroy
  #   @user = Gossip.find(params[:id])
  #   @user.destroy
  #   redirect_to root_path
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper

  include LikesHelper

  def is_mine(obj, user)
    obj.user == user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper


end

app/helpers/gossips_helper.rb
module GossipsHelper



end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/likes_helper.rb
module LikesHelper


  def already_liked?(user, gossip)
    Like.where(user_id: user.id, gossip_id: gossip.id).exists?
  end

  def get_like(user, gossip)
    Like.find_by(user_id: user.id, gossip_id: gossip.id)
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
	  if session[:user_id].present?
	    current_user = User.find_by(id: session[:user_id])
	  elsif cookies[:user_id].present?
	    user = User.find_by(id: cookies[:user_id])
	    if user && user.remember_digest.present? && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
	      log_in user
	      current_user = user
	    end
	  end
	end


  def log_in(user)
    session[:user_id] = user.id
  end

	def remember(user)
	  remember_token = SecureRandom.urlsafe_base64
	  user.remember(remember_token)
	  cookies.permanent[:user_id] = user.id
	  cookies.permanent[:remember_token] = remember_token
	end

	def forget(user)
		user.update(remember_digest: nil)
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out(user)
		session.delete(:user_id)
		forget(user)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjectFirstViews</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <%= link_to "The Gossip Project", root_path, :class =>"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", root_path, :class =>"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Team", team_path, :class =>"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, :class =>"nav-link" %>
          </li>

        </ul>
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
            <div class="dropdown">
              <li class="dropdown-toggle nav-item nav-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Bienvenue <%= current_user.first_name %>
              </li>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <li class="nav-item">
                  <%= link_to "Créer un gossip", new_gossip_path, class: "dropdown-item" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Profil", user_path(current_user.id), class: "dropdown-item" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: "dropdown-item" %>
                </li>
              </div>
            </div>


          <% else %>
            <li class="nav-item">
              <%= link_to "S'inscrire", new_user_path, :class =>"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Se connecter", new_session_path, :class =>"nav-link" %>
            </li>
            <% end %>
          </ul>
      </div>
    </nav>
    <%= yield %>

      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

</html>